### ISSUE TITLE
Missing picons

### ISSUE THREAD

**Issue by adrianmihalko** [s3n0/e2plugins#14]
Ahoj,

I would like to report to you:

**missing picons for channels (Hungarian channels 0.8W):**

```
Travel Channel
1:0:1:A5A:7:1:E080000:0:0:0:

Digi World
1:0:1:3FD:4:1:E080000:0:0:0:

Digi Animal World
1:0:1:177A:7:1:E080000:0:0:0:

DaVinci Learning 
1:0:1:B90:7:1:E080000:0:0:0:

Eurosport 2 HU
1:0:1:B22:7:1:E080000:0:0:0:

H!T Music RO
1:0:1:3EC:7:1:E080000:0:0:0:

ProTV International
1:0:1:B9A:7:1:E080000:0:0:0: 
```

**Wrong picon:**
```
Viasat Explore HD
1:0:19:7984:2C7:600:E080000:0:0:0:
```

![1_0_19_7984_2C7_600_E080000_0_0_0](https://user-images.githubusercontent.com/733361/149546261-41657117-305a-4ea7-92d7-dc2656ee0335.png)

If you have some time, please add these.

Enabled sattelites:

- antiksat
- digiczsk
- dvbtCZSK
- freeSAT
- orangesat
- skylink
- 0.8W

**Comment by s3n0** [comment]
Hi.

You need to report this to a discussion forum:

* https://picon.cz/forum/
* https://www.linuxsat-support.com/thread/124700-picons-by-chocholou%C5%A1ek/?pageNo=1
* http://www.ab-forum.info/viewtopic.php?f=417&t=74780&sid=7248cd82d3db793bb6beab8a3ed5bb92

I am (s3n0) just a developer of the enigma2 plugin.

Chocholousek is the creator and designer of these picons.

**Comment by adrianmihalko** [comment]
Thanks for the info.

**Comment by adrianmihalko** [comment]
This is the answer:

"All the services you write here contain the correct picon. There is nothing to fix, check it out! This also applies to Viasat Explore HD.

I have no idea what and where you want to add!
antiksat is a Slovak provider for 16E !!!
digiczsk CZ and SK only!
dvbtCZSK CZ and SK only!
freeSAT is only for the needs of CZ and SK, I have no idea what the content of the Hungarian UPC.
orangesat - Why edit orangesat which does NOT exist from this Sunday.
skylink There is a service on 23E not 0.8w

I do not understand this request at all !!!
"

So I don't know what to do now. In any case, these picon are missing for channels on 0.8W.

**Comment by adrianmihalko** [comment]
I am sorry, it was a false report. Somehow I changed the download location in the plugin, while OpenPli using the /usr/share/enigma2/picon/​. It is all good now.​
