### ISSUE TITLE
Nelze spustit na DM7020HD

### ISSUE THREAD

**Issue by pkingcz** [s3n0/e2plugins#15]
Mám problém se spuštěním pluginu na svém Dreamboxu DM7020HD. Moc tomu nerozumím, zasílám 2 crashlogy.
Díky
[enigma2_crash_1642443358.log](https://github.com/s3n0/e2plugins/files/7884056/enigma2_crash_1642443358.log)
[enigma2_crash_1642443496.log](https://github.com/s3n0/e2plugins/files/7884057/enigma2_crash_1642443496.log)

**Comment by s3n0** [comment]
Ahoj.

Diky za report chyby.

Takže používaš **Open Dreambox 2.0.0** image ... teda ak som to prečítal správne, z tvojho crash-LOG. 

Chyba v hardwari rozhodne nie je. Chyba sa vôbec netýka samotného zariadenia (DM7020HD). Podľa tvojho crash-LOG je chyba tu:
`AttributeError: 'eListbox' object has no attribute 'setFont'`

Hm... tak... čože to zase tí developeri Open Dreamboxu namajstrovali, že `eListbox` nepozná `setFont` ? :)

Pravdepodobne tvoj SKIN alebo tvoja Enigma2 distribúcia (Open Dreambox 2.0.0) si nevedia poradiť s konkrétným spôsobom určovania typu fontu + veľkosti fontu. Z pre mňa zatiaľ neznámeho dôvodu, nefunguje zmena fontu touto štandardnou metódou, ktorá dobre funguje v takmer každej inej Enigma2 distribúcii. 

Skúsiť niečo môžme... ale... neviem, ako sa to prejaví potom aj na ostatných Enigma2 distribúciach. Nepoznám vôbec Open Dreambox 2.0.0, ale skúsim niečo pohľadať na webe.

Poprípadne môžme skúsiť úplne vyhodiť nastavenie typu fontu + veľkosti fontu. Ale to môže mať katastrofálne následky na výzor Plugin-MENU ako som už napísal - možno v prípade mnohých ďalších distribúcií Enigma2 :). To by trebalo následne otestovať na veľa ďalších Enigma2 distribúciach, ako to bude vyzerať. Väčšina Enigma2 distribúcií popríp. samotných SKIN-ov si toto vedia "ošéfovať" aj sami (automaticky), ale neplatí to žiaľ vždy. A potom tam môžeš napríklad uvidieť šialenú veľkosť písma alebo veľmi dlhé texty, čo presahujú ďaleko za konfiguračné okno pluginu :).

**Comment by s3n0** [comment]
Ahoj.

Diky za report chyby.

Takže používaš **Open Dreambox 2.0.0** image a SKIN **Ai.HD.ModV2** ... teda ak som to správne prečítal, z tvojho crash-LOG. 

Chyba v hardwari rozhodne nie je. Chyba sa vôbec netýka samotného zariadenia (DM7020HD). Podľa tvojho crash-LOG je chyba tu:
`AttributeError: 'eListbox' object has no attribute 'setFont'`

Hm... tak... čo to zase tí developeri Open Dreamboxu namajstrovali, že `eListbox` nepozná `setFont` ? :)

V plugine už bol skôr pridaný patch pre tento účel. Jedná sa o vyňatie určovania typu+veľkosti fontu, ak je zdetekovaná novšia verzia Enigma2 jadra (OE 2.2+). Takže buďto nefunguje správne táto detekcia novšieho Enigma2 jadra alebo používaš starú verziu Chocholousek Picons pluginu, v ktorom tento patch ešte neexistoval.

Pravdepodobne tvoj SKIN alebo tvoja Enigma2 distribúcia (Open Dreambox 2.0.0) si nevedia poradiť s použitým spôsobom určenia typu fontu a veľkosti fontu. Z pre mňa zatiaľ neznámeho dôvodu, nefunguje zmena fontu touto štandardnou metódou, ktorá však funguje korektne v takmer každej Enigma2 distribúcii. 

Našiel som na internete aj nový spôsob určenia fontu pre `eListbox` a ten by mal fungovať v nových Enigma2 jadrách, ale nieje zaručené, že to tak pochopí každá Enigma2 distribúcia. Neexistujú žiaľ len originálne firmware od Dreambox-u, ale aj všakovaté odvodeniny nových Enigiem. A tie sa môžu správať zase nejako ináč.

**Comment by s3n0** [comment]
Ahoj.

Diky za report chyby.

Takže používaš **Open Dreambox 2.0.0** image a SKIN **Ai.HD.ModV2** ... teda ak som to správne prečítal, z tvojho crash-LOG. 

Chyba v hardwari rozhodne nie je. Chyba sa vôbec netýka samotného zariadenia (DM7020HD). Podľa tvojho crash-LOG je chyba tu:
`AttributeError: 'eListbox' object has no attribute 'setFont'`

Z pre mňa zatiaľ neznámeho dôvodu nefunguje zmena fontu štandardnou metódou aj v nových Enigma2 jadrách (OE 2.2+). Avšak funguje korektne v takmer každej starej Enigma2 distribúcii so starým jadrom OE 1.6 - OE 2.0.

Do pluginu bol už dávnejšie pridaný patch, práve pre tento účel. Jedná sa o vyňatie typu a veľkosti fontu, ak je zdetekovaná nejaká novšia verzia Enigma2 jadra (OE 2.2+). 

Takže pravdepodobne v tvojom prípade, nefunguje táto detekcia novšieho Enigma2 jadra správne. Rád by som zistil prečo, ale nemám k dispozícii Open Dreambox :(.

Našiel som na internete aj nový spôsob určenia fontu pre `eListbox` a ten by mal fungovať v nových Enigma2 jadrách, ale nie je zaručené, že to tak pochopí každá nová Enigma2 distribúcia. Neexistujú žiaľ len originálne firmware od Dreambox-u, ale aj všakovaté odvodeniny týchto nových Enigiem. A tie sa môžu správať zase nejako ináč.

**Comment by s3n0** [comment]
Ahoj.

Diky za report chyby.

Takže používaš **Open Dreambox 2.0.0** image a **Ai.HD.ModV2** SKIN ... teda ak som to správne prečítal, z tvojho crash-LOG. 

Chyba v hardwari rozhodne nie je. Chyba sa vôbec netýka samotného zariadenia (DM7020HD). Podľa tvojho crash-LOG je chyba tu:
`AttributeError: 'eListbox' object has no attribute 'setFont'`

Z pre mňa zatiaľ neznámeho dôvodu nefunguje zmena fontu štandardnou metódou aj v nových Enigma2 jadrách (OE 2.2+). Avšak funguje korektne v takmer každej starej Enigma2 distribúcii so starým jadrom OE 1.6 - OE 2.0.

Do pluginu bol už dávnejšie pridaný patch, práve pre tento účel. Jedná sa o vyňatie typu a veľkosti fontu, ak je zdetekovaná nejaká novšia verzia Enigma2 jadra (OE 2.2+). 

Takže pravdepodobne v tvojom prípade, nefunguje korektne táto detekcia jadra. Rád by som zistil prečo, ale nemám k dispozícii Open Dreambox na otestovanie kódu :(.

Našiel som na internete aj nový spôsob určenia fontu pre `eListbox` a ten by mal fungovať v nových Enigma2 jadrách, ale nie je zaručené, že to tak pochopí každá nová Enigma2 distribúcia. Neexistujú žiaľ len originálne firmware od Dreambox-u, ale aj všakovaté odvodeniny týchto nových Enigiem. A tie sa môžu správať zase nejako ináč.

**Comment by s3n0** [comment]
Otestuj prosim najnovsiu verziu pluginu - vydanu dnes. Aj ked sa trochu obavam, ze teraz zas mozu vznikat problemy s detekciou novsieho jadra, prave u inych Enigma2 distribucii, ak to aj v konkretne tej tvojej Enigma2 distribucii bude fungovat teraz uz spravne.

**Comment by pkingcz** [comment]
Ahoj, tak jsem zkusil novou verzi a vypadá to stále stejné 👎
Já tomu moc nerozumím, ale nějaké úpravy bych zvládnul - což nějaká úprava v tom skinu, pevně vložit tu proměnnou...
Díky

**Comment by s3n0** [comment]
Ahoj. 

Nemas nejaky svoj Skype ucet napriklad ? Tam by sme si mohli napisat. Inych komunikacnych klientov zial nepouzivam :D.

No tak on je problem uplne inde, to nema nic s nejakou "fixnou hodnotou". Na to aby som to odladil, ze co vlastne s tym mas... by som potreboval pristup k tvojmu set-top boxu cize k tvojej Enigme :) - t.j. terminalove pripojenie (ssh/telnet) a tiez pripojenie http na OpenWebif v set-top boxe. Ak mi veris, ak to vies zabezpecit, tak cez Skype napriklad mozme skusit toho viac urobit s tvojou Enigmou. 

Ja zial doma nemam tvoju Enigmu, takze neviem, kde presne je v tvojom pripade problem. Ale myslim si, ze problem bude v detekcii jadra Enigmy. Nove jadra respektive novsie Enigma distribucie funguju trochu inac. Do konfiguracneho LIST-MENU sa zial musi typ fontu a velkost fontu "posielat" odlisnou metodou, nez v doterajsich Enigmach. Viem jak sa to robi, ale to zase nie je tak uplne ciste riesenie, pretoze niektore Enigma distribucie aj ked budu bezat s novym jadrom, tak vzdy mozu mat este aj tieto stare sposoby pre urcenie fontu. A to by zase zlyhalo, pretoze ja by som detekoval nove jadro ale bol by tam stary sposob urcenia fontu. Preto to mam v kode vyriesene tak, ze poziadavok na zmenu fontu v konfiguracnej ponuke, proste vymazem a je po probleme :). Akurat bez urcenia velkosti a typu pisma, to moze vyzerat (v niektorych malo SKINoch) dost blbo.

Alebo... dalsia moznost... ak mas cas a ak to vies a zvladnes... tak prosim vyskusaj spustit v terminali aspon nasledovny command. Po terminalovom pripojeni (cez ssh alebo telnet) k tvojmu set-top boxu, skus napisat jednoducho: 
`ls -d /etc/*pkg`
... a okopiruj mi sem potom vystup z terminalu. Ale to je len prvy krok... a to mi nebude stacit :).

**Comment by s3n0** [comment]
Ahoj. 

Nemas nejaky svoj Skype ucet napriklad ? Tam by sme si mohli napisat. Inych komunikacnych klientov zial nepouzivam :D.

No tak on je problem uplne inde, to nema nic s nejakou "fixnou hodnotou". Na to aby som to odladil, ze co vlastne s tym mas... by som potreboval pristup k tvojmu set-top boxu cize k tvojej Enigme :) - t.j. terminalove pripojenie (ssh/telnet) a tiez pripojenie http na OpenWebif v set-top boxe. Ak mi veris, ak to vies zabezpecit, tak cez Skype napriklad mozme skusit toho viac urobit s tvojou Enigmou. 

Ja zial doma nemam tvoju Enigmu, takze neviem, kde presne je v tvojom pripade problem. Ale myslim si, ze problem bude v detekcii jadra Enigmy. Nove jadra respektive novsie Enigma distribucie funguju trochu inac. Do konfiguracneho LIST-MENU sa zial musi typ fontu a velkost fontu "posielat" odlisnou metodou, nez v doterajsich Enigmach. Viem jak sa to robi, ale to zase nie je tak uplne ciste riesenie, pretoze niektore Enigma distribucie aj ked budu bezat s novym jadrom, tak vzdy mozu mat este aj tieto stare sposoby pre urcenie fontu. A to by zase zlyhalo, pretoze ja by som detekoval nove jadro ale bol by tam stary sposob urcenia fontu. Preto to mam v kode vyriesene tak, ze poziadavok na zmenu fontu v konfiguracnej ponuke proste vymazem, ked bolo detekovane novsie jadro Enigmy (uplne nove Enigma distribucie, ako aj komercne Enigma distribucie original od Dreamboxu) a hned je po probleme :) ... akurat ze bez urcenia velkosti pisma a typu pisma, to moze vyzerat dost blbo (v niektorych malo SKINoch).

Alebo... dalsia moznost... ak mas cas a ak to vies a zvladnes... tak prosim vyskusaj spustit v terminali aspon nasledovny command. Po terminalovom pripojeni (cez ssh alebo telnet) k tvojmu set-top boxu, skus napisat jednoducho: 
`ls -d /etc/*pkg`
... a okopiruj mi sem potom vystup z terminalu. Ale to je len prvy krok... a to mi nebude stacit :). 

Alebo sa to da zistit aj cez FTP pripojenie... co je este jednoduchsie... jedna sa mi o to, ze ci tam mas `dpkg` alebo `opkg` spravcu balickov (a to napriklad aj nahliadnutim do pod-adresara `/etc`) popripadne objavis ineho spravcu balickov, ako je napr. `ipkg`, ale ten sa myslim nepouziva v linuxovych set-top boxoch, hmm.
