### ISSUE TITLE
IPK Install Error Open ATV 7.2

### ISSUE THREAD

**Issue by tovdave** [s3n0/e2plugins#16]
I get this error when installing the ipk:

extensions-epg-export_1.5-rO_all.ipk: Unrecognized archive format (errno=84)
* open_outer: Failed to open package /media/hdd/enigma2-plugin-extensions-epg-export_1.5-rO_all.ipk: Unrecognized archive format (errno=84)
* pkg_extract_control_file_to stream: Failed to extract control.tar. * from package /media/hdd/enigma2-plugin-extensions-epg-export_1.5-rO_all.ipk'.

Can someone help me?

**Comment by s3n0** [comment]
Hi. You probably downloaded the wrong IPK file. Try to open the downloaded IPK file on your PC and look at its contents. Check if there is no HTML code inside the file. If so, you downloaded the IPK file incorrectly. It is also not recommended to install online, directly with the help of a URL inserted into the OPKG (package manager).
