### ISSUE TITLE
Openatv 7.3

### ISSUE THREAD

**Issue by ghost** [s3n0/e2plugins#17]
Constant error on downloading zip file
No picon prewiev
Reported by 2 ppl me and friend on 2 different devices

**Comment by s3n0** [comment]
Hi,

thanks for the bug report... but... I also need to see some debug from Enigma2. It works everywhere, except for you. So the problem must be only with you and you need to find out why. 

If there is no picon preview file, the internet connection with a server is probably not working either or you are trying to connect to the internet via a VPN network (set up in a WiFi router or set-top box). 

The error can really be anywhere. It requires diagnostics, but primarily the debug log from Enigma2. Activate the debug in the OpenATV settings, then reboot the set top box, trigger an error in the plugin, and get the debug log file created (from the set top box - from "/home/root/logs" folder).
