### ISSUE TITLE
ChocholousekPicons - nefunkcne update pri OE2.5

### ISSUE THREAD

**Issue by Ciksa** [s3n0/e2plugins#2]
Pri OE2.5 sa stale ziadne update pluginu na vyssiu verziu nekona ale miesto toho je plugin zmazany !

**Comment by s3n0** [comment]
Ahoj, dik za report.

Ano viem o tomto probleme uz niekolko dni. Bohuzial nevlastnim ziaden prijmac, na ktorom by bolo mozne rozbehnut OE2.5 image (nevlastnim ziaden Dreambox).

Takze nie je v mojich silach najst presnu pricinu tohto problemu tak ako by sa to patrilo. Zatial je pouzite iba docasne, no za to ucinne riesenie problemu - thx to Chocholousek, ktory to pre mna otestoval aspon ako nieco malo na dialku, teda to co sa aspon dalo otestovat. 

Spravca balickov `dpkg` sa bohuzial nechova rovnako, ako spravca `opkg` a ked mu zadas argument pre instalaciu balicka s vyssiou verziou nez ta, ktora tam je uz nainstalovana, tak tento `dpkg` z nezistitelnej priciny preinstaluje balicek, ale zanecha zmazany obsah zlozky, v ktorej by mal byt plugin. Debian/control subory boli okontrolovane tiez uz viac krat a zdaju sa byt v najlepsiom poriadku, vcetne ich priority volania pred + po instalacii. Spravca `opkg` ak dostane prikaz na instalovanie balicku s novsiou verzieou nez ta ktora uz je nainstalovana, tak vykona jednoduchy reinstall na vyssiu verziu, uplne bezproblemov. Zial `dpkg` manager s tym ma nejaky problem. Preto teraz pracuje `dpkg` manager v pripade aktualizacie pluginu v dvoch krokoch - najprv je plugin odinstalovany (`dpkg -r`)  a hned v druhom kroku sa znova nainstaluje (`dpkg -i`). Tento sposob funguje, avsak nie je to standardny sposob pre upgradovanie na vyssiu verziu. Mozno by to vedel upgradovat skor `apt` a nie `dpkg`. Kedze nemam k dispozicii ziaden pristroj s OE2.5, na ktorom by som to mohol testovat, tak to je zatial aspon nejak vyriesene.

Som len skromny vyvojar a nie znalec vsetkych vymyslenych Enigiem na svete :). Ony sa lisia vsetky Enigmy aj v jednotlivych distribuciach a nie to este vo svojom OE jadre. Zdalo by sa, ze najnovsie OE2.5 a OE2.6 budu tiez konecne nejake ustalene standardy Dreambox-u, ale aj tam existuju nejake odlisnosti. Najvacsie problemy robia predovsetkym SKINy (kompatibilita medzi nimi z pohladu vyvojara). 

Cize vo verzii 191118 je tento problem aktualizacie priamo cez konfiguraciu Chocholousek pluginu aspon nejak vyrieseny.
