### ISSUE TITLE
Najnovsia verzia pluginu 2.0.200424 - pad enigmy po spusteny pluginu

### ISSUE THREAD

**Issue by Ciksa** [s3n0/e2plugins#6]
Pri spusteny najnovsej verzie dochadza k padu enigmy. Prikladam crash log enigmy. Box je Octagon SF 8008 a image je posledne OpenATV 6.4 . Ako by na pozadi nieco hladal alebo sa snazil na nieco pripojit.

**Comment by s3n0** [comment]
To uz by malo byt vyriesene. Chyba konkretne _**UnboundLocalError: local variable 'new_file' referenced before assignment**_ vznikala preto, ze bol na drive.google ulozeny subor pod chybnym nazvom (pismeno "s" na konci nazvu). Tento subor "**permalinks**" sa stahuje zo servera ihned ako vojdes do ChocholousekPicons pluginu, za ucelom zistenia a aktualizovania dalsich potrebnych dat. Skus ci to funguje. Thx.

**Comment by Ciksa** [comment]
Uz to je OK. Dakujem
