### ISSUE TITLE
neda sa nainstalovat na BH 3.0.9.P 

### ISSUE THREAD

**Issue by er2or** [s3n0/e2plugins#7]
Minimalne 2 posledne verzie sa nedaju nainstalovat na VU+ Duo4k BH 3.0.9P.
Pri instalacii cez menu sa zdalo, ze ipk nainstalovalo, po restarte ale nieje nikde v menu.
Pri instalacii z CLI:
root@vuduo4k:/var/volatile/tmp# opkg install enigma2-plugin-extensions-chocholousek-picons_3.1.200926_all.ipk 
Collected errors:
 * deb_extract: enigma2-plugin-extensions-chocholousek-picons_3.1.200926_all.ipk: invalid magic
 * pkg_init_from_file: Failed to extract control file from enigma2-plugin-extensions-chocholousek-picons_3.1.200926_all.ipk.
root@vuduo4k:/var/volatile/tmp# opkg install enigma2-plugin-extensions-chocholousek-picons_3.1.201103_all.ipk 
Collected errors:
 * deb_extract: enigma2-plugin-extensions-chocholousek-picons_3.1.201103_all.ipk: invalid magic
 * pkg_init_from_file: Failed to extract control file from enigma2-plugin-extensions-chocholousek-picons_3.1.201103_all.ipk.

V com moze byt problem?

Diky!

**Comment by s3n0** [comment]
Ahoj. 

No tazko povedat. BlackHole image si mysli, ze je IPK balicek nejakym sposobom poskodeny. Netusim preco. Vsade inde to funguje. Je sto percent dobre stiahnuty z internetu ? Neposkodil tento tvoj IPK subor napriklad nejaky antivirus svojim zasahom do suboru, pocas jeho stahovania z internetu ? Heuristicka analyza uz davno nie je to, co bejvavalo pred 20 rokmi a moze nespravne detekovat podobny kod, akoby to bol napriklad nejaky virus.

Odinstaloval si tiez predosly plugin este pred instalaciou noveho (pre istotu) ? Kedze to robis takto manualne. Nasledne zrestartujes Enigmu a pouzijes `opkg update` v Shell a az potom skusis nainstalovat novy plugin. Alebo ako to presne instalujes (postup) ? Otestuj nainstalovanie pluginu cez automatizovane scripty, priamo z github:
```
# Download and install the latest version (.deb / .ipk):
wget -qO- --no-check-certificate "https://github.com/s3n0/e2plugins/raw/master/ChocholousekPicons/online-setup" | bash -s install

# Uninstall (.deb / .ipk):
wget -qO- --no-check-certificate "https://github.com/s3n0/e2plugins/raw/master/ChocholousekPicons/online-setup" | bash -s uninstall
```

**Comment by s3n0** [comment]
Ahoj. 

No tazko povedat. BlackHole image si z nejakeho dovodu mysli, ze IPK balicek je nejakym sposobom poskodeny. Netusim preco. V inych Enigmach to funguje. Subor bol stiahnuty z internetu bez chyb ? Neposkodil tento IPK subor napriklad nejaky antivirus ? Mohol by byt subor poskodeny zasahom antiviru do suboru, pri detekcii potencialneho skodliveho kodu, pri stahovani z internetu. Heuristicka analyza uz nie je to, co bejvavalo pred 20 rokmi. Antivirus moze hocikedy nespravne zdetekovat zhodny kod s nejakym virom a tento usek kodu zo suboru nasledne vymaze.

Kedze to robis takto manualne... odinstaloval si tiez predoslu verziu pluginu ChocholousekPicons, este pred instalaciou noveho (pre istotu) ? Nasledne potom zrestartujes Enigmu a az potom skusis nainstalovat novy plugin. Alebo napis postup, ako presne instalujes plugin.

Otestuj este automatizovany instalacny shell-script priamo z mojho github-u. Tento online script zaroven odinstaluje plugin a vymaze nastavenia ChocholousekPicons pluginu z "/etc/enigma2/settings" suboru:
```
# Download and install the latest version (.deb / .ipk):
wget -qO- --no-check-certificate "https://github.com/s3n0/e2plugins/raw/master/ChocholousekPicons/online-setup" | bash -s install

# Uninstall (.deb / .ipk):
wget -qO- --no-check-certificate "https://github.com/s3n0/e2plugins/raw/master/ChocholousekPicons/online-setup" | bash -s uninstall
```

Este ma napadlo, ze mozno je treba vlozit vnoreny adresar `CONTROL` v instalacnom balicku. V tomto adresari cisto teoreticky hlada spravca balickov u BlackHole subor `control`, ale nenajde ho. Tento vnoreny adresar `CONTROL` v IPK balicku nemam. Subory su postavene mimo tento adresar. Rovnako vela inych plugin vyvojarov tento adresar `CONTROL` nepouzivaju (resp. adresar `DEBIAN` pre balicky DEB) ... a fakt vsetko im funguje bez problemov. Uz som taketo IPK balicky niekde videl, ze je v nich vnoreny jak `CONTROL` adresar so suborom `control`, tak zaroven je tam druha kopia suboru (resp. dalsich potrebnych suborov) priamo v root-e .tar.gz archivu. Teraz len hadam moznu pricinu problemu a neviem ci by toto konkretne pomohlo. Trebalo by vyskusat. Musis sa mi ozvat ked tak ... a vyskusame to :). Cez OpenMultiboot v mojom set-top boxe totiz nefunguje BlackHole image.

**Comment by er2or** [comment]
Ahoj, vdaka za odpoved.

Toto bola prva instalacia pluginu, doteraz som iba nakopiroval picony
Tuto instalaciu som robil cez menu (manualne nakopirovat na stb a z menu dat instalovat). Pri instalacii som si nevsimol nic podozrive. Po reboote som vsak plugin nikde medzi pluginmi nenasiel.
Potom som uz stahoval ipk balicky cez wget priamo z boxu a instaloval cez opkg s vysledkom ako hore...

Skusil som install script ako si odporucil a vsetko zbehlo bez problemov, a po reboote je aj plugin tam kde ma byt...
Nic som pred tym nemazal ani neodinstaloval.

Uz to funguje, dkujem za tip na script.

-=er2or=-

**Comment by s3n0** [comment]
Nemas za co 😉. Kazdoadne dik aj za tvoj report chyby 👍. 

Je to zaujimavy pripad, ktory sa stal uz druhy krat, avsak prvy krat sa tykal NewNigma2. Nedavno na ab-forum (http://www.ab-forum.info/viewtopic.php?f=417&t=74780&sid=80f8e39db196ccaa005a7e8351b0c672&start=140) o tomto probleme pisal uzivatel @ROGIII ... kedze obcas tam nahliadnem (registracia nie je nastastie potrebna a toto diskusne vlakno patri v podstate Chocholouskovi, tvorcovi picon, takze on mi da vediet, ak by niekto ohlasil BUG), no a prave vyriesenim problemu bolo tiez pouzitie mojho instalacneho scriptu z github-u. Teda konkretne ten isty script, ktory som aj tebe poradil vyskusat. Tu je priamy link na kod
https://github.com/s3n0/e2plugins/blob/master/ChocholousekPicons/online-setup

Je to fakt zahada. Jedine, co ma napada, ze v com by mohla byt chyba, je poskodenie suboru IPK, pri jeho stahovani z internetu. Toto sa stava napriklad aj vtedy, ak das `opkg` spravcovi balickov nie vopred stahovany IPK subor, ale ak mu zadas ako argument priamo URL adresu na IPK online subor. No ty ako pises, si instaloval subor z "/tmp" adresara.

Ide mi o to zistit, ako sa poskodil subor ak vobec. Vies mi prosim ta poslat ten IPK subor, ktory sposoboval tieto problemy s nainstalovanim ? Mal by sa dat myslim aj vlozit sem, ako priloha / subor. Alebo ak mozes a dokazes to, sprav prosim kontrolny sucet napr. za pomoci TotalCommandera (CRC-32 sucet by mal postacovat) u oboch suborov - u toho co nefungoval, ako aj u toho suboru, ktory sa stiahne cez moj `online-setup` script... tu je vypis kodu do Shell, pre stiahnutie suboru do adresara "/tmp": 
```
PKGNAME="enigma2-plugin-extensions-chocholousek-picons"
VER="$(wget -qO- --proxy off --no-check-certificate https://github.com/s3n0/e2plugins/raw/master/ChocholousekPicons/src/version.txt)"
FNAME="${PKGNAME}_${VER}_all.$([ -d /etc/dpkg ] && echo -n 'deb' || echo -n 'ipk')"
wget -qO "/tmp/${FNAME}" --no-check-certificate "https://github.com/s3n0/e2plugins/raw/master/ChocholousekPicons/released_build/${FNAME}"
```
A potom porovnas vysledok kontrolneho suctu u oboch IPK suborov - ten co fungoval (stiahnes si ho tak, ako je uvedene v mojhom `online-setup` scripte) a ten co nefungoval. Musi sa zhodovat. Ak nie, vieme povedat na 100%, ze chyba je vo vadnom IPK subore. 

Uved este prosim aj to, z ktoreho zdroja si stahoval tento nefunkcny IPK subor a jakou metodou si ho stahoval (wget, curl, z ktorej URL adresy, ktory webovy browser si pouzil ak si stahoval v Desktop-ovom PC cez webovy browser).

Napriklad ako som zmienoval vyssie, pri antivirovych testoch sa moze subor falosne oznacit ako zavireny. Este horsi je potom pripadny scenar pri pokusoch o vyliecenie udajneho viru, nejakym automatom-antivirom. Alebo sa moze subor poskodit pri stahovani z internetu aj pri pouzivani roznych "urychlovacov stahovania dat" (napriklad komprimovanie dat cez FTP prenos  alebo nejake "specilitky" v nastaveniach routra). Ja chcem len zistit, z ktoreho zdroja si stahoval IPK subor a preco dorazil k tebe ako poskodeny. Teda ak naozaj je chyba v tom poskodzovani IPK suboru, pri jeho stiahnuti z internetu.

Diky.

**Comment by s3n0** [comment]
Nemas za co 😉. Kazdoadne dik aj za tvoj report chyby 👍. 

Je to zaujimavy pripad, ktory sa stal uz druhy krat, avsak prvy krat sa tykal NewNigma2. Nedavno na ab-forum (http://www.ab-forum.info/viewtopic.php?f=417&t=74780&sid=80f8e39db196ccaa005a7e8351b0c672&start=140) o tomto probleme pisal uzivatel @ROGIII ... kedze obcas tam nahliadnem (registracia nie je nastastie potrebna a toto diskusne vlakno patri v podstate Chocholouskovi, tvorcovi picon, takze on mi da vediet, ak by niekto ohlasil BUG), no a prave vyriesenim problemu bolo tiez pouzitie mojho instalacneho scriptu z github-u. Teda konkretne ten isty script, ktory som aj tebe poradil vyskusat. Tu je priamy link na kod shell-scriptu:
https://github.com/s3n0/e2plugins/blob/master/ChocholousekPicons/online-setup

Je to fakt zahada. Jedine, co ma napada, ze v com by mohla byt chyba, je poskodenie suboru IPK, pri jeho stahovani z internetu. Toto sa stava napriklad aj vtedy, ak zadas `opkg` spravcovi balickov ako argument priamo online URL adresu na nainstalovanie IPK suboru. Cize nie dopredu stiahnuty IPK subor, umiestneny na lokalnom disku / nejakej particii v set-top boxe. No ako pises, tak ty si instaloval subor z "/tmp" adresara. Takze toto sa teba netyka

Ide mi o to zistit, ako sa poskodil subor ak vobec. Vies mi prosim ta poslat ten IPK subor, ktory sposoboval tieto problemy s nainstalovanim ? Mal by sa dat myslim aj vlozit sem, ako priloha / subor. Alebo ak mozes a dokazes to, sprav prosim kontrolny sucet napr. za pomoci TotalCommandera (CRC-32 sucet by mal postacovat) u oboch suborov - u toho co nefungoval, ako aj u toho suboru, ktory sa stiahne cez moj `online-setup` script... tu je vypis kodu do Shell, pre stiahnutie suboru do adresara "/tmp": 
```
PKGNAME="enigma2-plugin-extensions-chocholousek-picons"
VER="$(wget -qO- --proxy off --no-check-certificate https://github.com/s3n0/e2plugins/raw/master/ChocholousekPicons/src/version.txt)"
FNAME="${PKGNAME}_${VER}_all.$([ -d /etc/dpkg ] && echo -n 'deb' || echo -n 'ipk')"
wget -qO "/tmp/${FNAME}" --no-check-certificate "https://github.com/s3n0/e2plugins/raw/master/ChocholousekPicons/released_build/${FNAME}"
```
A potom porovnas vysledok kontrolneho suctu u oboch IPK suborov - ten co fungoval (stiahnes si ho tak, ako je uvedene v mojhom `online-setup` scripte) a ten co nefungoval. Musi sa zhodovat. Ak nie, vieme povedat na 100%, ze chyba je vo vadnom IPK subore. 

Uved este prosim aj to, z ktoreho zdroja si stahoval tento nefunkcny IPK subor a jakou metodou si ho stahoval (wget, curl, z ktorej URL adresy, ktory webovy browser si pouzil ak si stahoval v Desktop-ovom PC cez webovy browser).

Napriklad ako som zmienoval vyssie, pri antivirovych testoch sa moze subor falosne oznacit ako zavireny. Este horsi je potom pripadny scenar pri pokusoch o vyliecenie udajneho viru, nejakym automatom-antivirom. Alebo sa moze subor poskodit pri stahovani z internetu aj pri pouzivani roznych "urychlovacov stahovania dat" (napriklad komprimovanie dat cez FTP prenos  alebo nejake "specilitky" v nastaveniach routra). Ja chcem len zistit, z ktoreho zdroja si stahoval IPK subor a preco dorazil k tebe ako poskodeny. Teda ak naozaj je chyba v tom poskodzovani IPK suboru, pri jeho stiahnuti z internetu.

Diky.

**Comment by chocholousek** [comment]
Zdravim, vstoupim do doskuse.
Jedno je ve vsech pripadech stejne, uzivatel se snazi instalovat poskozeny balicek, coz nemuze skoncit jinak nez chybou. Inu neni nad to instalovat balicek o kterem jsme si jisti ze je stazen dobre,  wget nebo curl a ja nevim co vsechno jsou rychle ale nemate jako uzivatel kontrolu ze je vse stazeno tak jak ma byt. Osobne si myslim ze si si poridil balik pres nejaky podobny nastroj a ten stahnul jen obycejne HTML, vysledek je jaky je.
Napriklad picon.cz je nastaven velmi restriktivne a pokud neni vse v "poradku" je odpoved v podobe HTML namisto balicku, beznym obrannym mechanizmem.

**Comment by er2or** [comment]
Ahoj,
Ad antivirus - pouzivam len Windows Security.
1. pokus o instalaciu - (w10 nb) http download poslednej verzie cez firefox, winscp upload na stb, instalacia cez menu. Priebeh instalacie standardny, ale po restarte plugin nebol nainstalovany.
2. pokus - priamo z stb wget z gitu - 2 posledne verzie, instalacia cez opkg s vysledkom vyssie. 
3. pokus - instalacia skriptom - uplne bez problemov a na prvy pokus...

Pripajam crc checky - tento som teraz stiahol z gitu cez firefox
[3.1.200926_ff.zip](https://github.com/s3n0/e2plugins/files/5702231/3.1.200926_ff.zip)

a tento som stahoval wgetom z gitu a instaloval cez opkg
[3.1.200926_wget.zip](https://github.com/s3n0/e2plugins/files/5702240/3.1.200926_wget.zip)

Subory nemaju rovnaku velkost...

@chocholousek - ano, to html by mohlo byt ten dovod chyby po stiahnuti wgetom, ale prvy pokus ipk som stahoval cez browser a instalacia aj ked sa tvarila ze prebehla v poriadku, nebola uspesna...

Planujem coskoro full flash update na BH 3.1.0 a vyskusam to na cistom image. Ak by boli dake chyby dam vediet...

**Comment by s3n0** [comment]
Dik za subory. Ten subor cez wget ak si vsimnes a otvoris to cez normalny textovy editor alebo cez hex-editor, uvidis vo vnutri suboru iba HTML kod. To je samorejme zle. Nema to byt HTML web-stranka, ale komplexny archiv (archivatorom `ar` spojene dva archivy `.tar.gz` a jeden jednoduchy ascii subor s nazvom `debian-binary`. IPK subor dokaze rozbalovat napriklad aj 7-zip archivator urceny pre Windows. V tomto pripade sa jedna o problem, ktory uz naznacil @chocholousek. Subor "firefox" je vsak v poriadku. Takze ak nefungoval ten, potom musel spravit chybu WinSCP. Ja osobne WinSCP nepouzivam a nenavidim. Je to jeden z tych druhov nastrojov, co sa snazia spustu veci robit nestandardne resp. podla seba... inymi slovami nieje tak moc blbuvzdorny, ako sa tvari. Ja pouzivam FTP klienta zabudovaneho v Total Commander-i. Ten je uplne super. WinSCP je pre mna osobne velmi neprehladny a chaoticky.

Co sa tyka toho stahovania suboru z internetu v tvojom pripade ... tak ja som mal na mysli skor presne detajly okolo toho - teda aky tvar mal `wget` prikaz, ktory si pouzil na stiahnutie suboru cez shell. Pouzil si tiez wget argument, pre odignorovanie SSL ? Tak ako aj ja, v mojom instalacnom online scripte ? Pretoze s tym SSL je furt nejaky problem ... teda co sa tyka stahovania suborov: wget VS github. A tiez ma zaujima, aky si pouzil presne zdroj stahovaneho IPK balicka - teda aky tvar mala URL adresa, ktoru si pouzil.

Mimochodom je tam uz novsia verzia pluginu https://github.com/s3n0/e2plugins/tree/master/ChocholousekPicons/released_build , ale ty si predpokladam pouzil starsiu verziu, kedze som ta vyslovene ziadal o pretestovanie tych IPK s ktorymi ti to nefungovalo resp. potom aj fungovalo. Za co este raz dakujem samozrejme. 

Teraz uz aspon vieme, kde bol problem a sice v tvojom `wget`. Zalezi este od konkretnej verzie pouziteho wget. Totiz wget nastroj zahrnuty do BusyBox, sa chova celkom inac, nez plnohodnotny wget nastroj. BusyBox je balik niekolkych ochudobnenych systemovych nastrojov, prave pre male orezane Linuxy, ktore sa vyuzivaju nanestastie aj v set-top boxoch (z dovodu obmedzenej velkosti interneho flash disku, vykonu hardwaru, velkosti RAM, atd.). Neviem ako to maju vyriesene chlapi od BlackHole. Jednoducho povedane, chovanie samotneho `wget` moze byt odlisne z Enigmy do Enigmy. Tam by bolo dobre pouzivat aj dalsie argumenty u toho `wget` prikazu, no nie kazda verzia wget (Enigmy) tymito rozsirenymi funkciami wget disponuje.

**Comment by s3n0** [comment]
Dik za subory. Ten subor cez wget ak si vsimnes a otvoris to cez normalny textovy editor alebo cez hex-editor, uvidis vo vnutri suboru iba HTML kod. To je samorejme zle. Nema to byt HTML web-stranka, ale komplexny archiv - cez `ar` nastroj spojene dva archivy `tar.gz` a k tomu patri este jeden maly textovy subor s nazvom `debian-binary`. IPK subor dokaze rozbalit pod Windowsom napriklad 7-zip archivator. V tomto pripade sa jedna o problem stiahnutia "web-stranky" a nie samotneho binarneho suboru z github-u. Tento problem uz naznacil aj @chocholousek. Subor stiahnuty cez firefox je vsak v poriadku. Takze ak nefungoval ani tento "firefox subor", potom musel zase spravit chybu WinSCP, ked odosielal IPK subor do set-top boxu. Alebo si s tym nevedelo poradit GUI Enigmy BlackHole (moznych je vela scenarov... ako napriklad potrebne pristupove prava k suboru aj ked je umiestneny v "/tmp" zlozke alebo vymysliet by sa dal hocijaky iny mozny problem pri instalovani cez GUI v BlackHole).

Ja osobne WinSCP nepouzivam. Je to jeden z tych druhov nastrojov, co sa snazia spustu veci robit nestandardne resp. podla seba... inymi slovami nieje tak moc blbuvzdorny, ako sa tvari. Ja pouzivam FTP klienta zabudovaneho v Total Commander-i. Ten je uplne super. WinSCP je pre mna osobne velmi neprehladny a chaoticky.

Co sa tyka toho stahovania suboru z internetu v tvojom pripade ... tak ja som mal na mysli skor presne detajly okolo toho - teda aky tvar mal `wget` prikaz, ktory si pouzil na stiahnutie suboru cez shell. Pouzil si tiez wget argument, pre odignorovanie SSL ? Tak ako aj ja, v mojom instalacnom online scripte ? Pretoze s tym SSL je furt nejaky problem ... teda co sa tyka stahovania suborov: wget VS github. A tiez ma zaujima, aky si pouzil presne zdroj stahovaneho IPK balicka - teda aky tvar mala URL adresa, ktoru si pouzil.

Mimochodom je tam uz novsia verzia pluginu https://github.com/s3n0/e2plugins/tree/master/ChocholousekPicons/released_build , ale ty si predpokladam pouzil starsiu verziu, kedze som ta vyslovene ziadal o pretestovanie tych IPK s ktorymi ti to nefungovalo resp. potom aj fungovalo. Za co este raz dakujem samozrejme. 

Teraz uz aspon vieme, kde bol problem a sice v tvojom `wget`. Zalezi este od konkretnej verzie pouziteho wget. Totiz wget nastroj zahrnuty do BusyBox, sa chova celkom inac, nez plnohodnotny wget nastroj. BusyBox je balik niekolkych ochudobnenych systemovych nastrojov, prave pre male orezane Linuxy, ktore sa vyuzivaju nanestastie aj v set-top boxoch (z dovodu obmedzenej velkosti interneho flash disku, vykonu hardwaru, velkosti RAM, atd.). Neviem ako to maju vyriesene chlapi od BlackHole. Jednoducho povedane, chovanie samotneho `wget` moze byt odlisne z Enigmy do Enigmy. Tam by bolo dobre pouzivat aj dalsie argumenty u toho `wget` prikazu, no nie kazda verzia wget (Enigmy) tymito rozsirenymi funkciami wget disponuje.
